env:
  - ANSIBLE_VERSION='ansible>=2.2,<2.3'
  - ANSIBLE_VERSION='ansible>=2.3,<2.4'
  - ANSIBLE_VERSION='ansible>=2.4,<2.5'
  - ANSIBLE_VERSION='ansible>=2.5b,<2.6'

matrix:
  allow_failures:
    - env: ANSIBLE_VERSION='ansible>=2.5b,<2.6'

sudo: required

dist: trusty

language: python

install:
  - pip install "$ANSIBLE_VERSION"

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
