---

- name: HOSTNAME
  hostname:
    name: "{{ fbs_hostname }}"

- name: LINEINFILE | hostname in /etc/rc.conf
  lineinfile:
    regexp: '^hostname="'
    line: 'hostname="{{ fbs_hostname }}"'
    dest: /etc/rc.conf

- name: TEMPLATE | Cleanup /etc/hosts
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
  when: fbs_clean_hosts
