---

- name: INCLUDE | Prepare system
  include: prepare.yml

- name: INCLUDE | Configure packages
  include: packages.yml

- name: INCLUDE | Set hostname
  include: hostname.yml
  when: fbs_set_hostname

- name: INCLUDE | Manage system users
  include: user.yml

- name: TIMEZONE | Set
  timezone:
    name: "{{ fbs_timezone }}"
  when: fbs_set_timezone

- name: INCLUDE | Install NTP damon
  include: ntp.yml
  when: fbs_set_ntp

- name: INCLUDE | Misc system configuration
  include: system.yml
