---

- name: PKGNG | Install NTP daemon
  pkgng:
    name: "ntp"
    state: present

- name: TEMPLATE | Deploy NTPd configuration file
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntpd

- name: SERVICE | Enable NTP service
  service:
    name: ntpd
    enabled: yes
    state: started
