---

- name: COPY | dotfiles for root
  copy:
    src: "{{ item }}"
    dest: "/root/.{{ item }}"
  with_items:
    - "bashrc"
    - "vimrc"
    - "screenrc"
    - "gitconfig"
  when: fbs_use_dotfiles

- name: SYSCTL | Tuning
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ fbs_sysctl_config }}"

- block:

  - name: PKGNG | Install microcode
    pkgng:
      name: devcpu-data

  - name: SERVICE | Enable microcode service
    service:
      name: microcode_update
      enabled: yes

  when: fbs_microcode
